### ISSUE TITLE
The search box in blog section does not work

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-website#108]
![image](https://github.com/user-attachments/assets/072cd2c5-f254-418b-b3c0-d3ab0fcc52a1)

**Comment by grmbyrn** [comment]
Hi @josecelano the search is working for me on Chrome and Safari. I also put it into BrowserStack and the search worked on all the browsers I tested it on.

![Screenshot 2024-11-08 at 13 07 15](https://github.com/user-attachments/assets/28cc077f-8dc1-4c69-bfd2-abf8352ef34b)

**Comment by josecelano** [comment]
Hey @grmbyrn it seems it only happens if you try to search first for something with no results:

1. Load the page https://torrust.com/blog
2. Type `unity` and click return
3. Remove the text `unity`
4. Type `bencode`

Nothing happens.

**Comment by grmbyrn** [comment]
> Hey @grmbyrn it seems it only happens if you try to search first for something with no results:
> 
> 1. Load the page https://torrust.com/blog
> 2. Type `unity` and click return
> 3. Remove the text `unity`
> 4. Type `bencode`
> 
> Nothing happens.

Hi @josecelano I see the issue now. I'll have a look at it.
