### ISSUE TITLE
Minor bugs in homepage

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-website#12]
### Link to demo

Links to the demo don't work.

![image](https://github.com/user-attachments/assets/b4671c6f-4477-4284-a605-935ce1dce162)

### Learn more

Links to specific Index and Tracker pages don't work

![image](https://github.com/user-attachments/assets/d31bdf79-e877-435a-8d9c-f1ed784b374f)

### Number of latest articles

Current:

![image](https://github.com/user-attachments/assets/cb54ecf2-ece2-441d-8084-4e14726cbfbe)

Expected:

![image](https://github.com/user-attachments/assets/5354ec20-2dd3-4629-9dbe-5599d0c1cd47)

**Comment by josecelano** [comment]
Hi @grmbyrn links are not fixed yet.

**Comment by grmbyrn** [comment]
> Hi @grmbyrn links are not fixed yet.

Hi @josecelano What are the links you would like to provide here?

**Comment by josecelano** [comment]
> > Hi @grmbyrn links are not fixed yet.
> 
> Hi @josecelano What are the links you would like to provide here?

Index:

- Live demo: https://index.torrust-demo.com
- Learn more: /torrent-index
- v3.0.0: https://github.com/torrust/torrust-index/releases

Tracker:

- Live demo: https://index.torrust-demo.com
- Learn more: /torrent-tracker
- v3.0.0: https://github.com/torrust/torrust-tracker/releases
