### ISSUE TITLE
Incorrect layout of the `/contributors` page; the header and footer are duplicated.

### ISSUE THREAD

**Issue by Binlogo** [torrust/torrust-website#121]
https://torrust.com/contributors
![image](https://github.com/user-attachments/assets/eff09fe2-194e-4b8f-b519-57fe82d4ae5a)

**Comment by josecelano** [comment]
Thank you @Binlogo, I think we agree on removing that page in one of our latest meetings.

Are we finally going to remove that page @da2ce7 @cgbosse @mario-nt, @grmbyrn?

**Comment by josecelano** [comment]
I think I mentioned we could do something like:

![image](https://github.com/user-attachments/assets/331016a5-bc0d-4b5c-a15c-47b643903d0a)

Getting the list of contributors and their avatars automatically from GitHub API.

**Comment by da2ce7** [comment]
I think that making it dynamic on the GitHub API would be much better than what we have now :)

https://github.com/torrust/torrust-website/issues/124

**Comment by grmbyrn** [comment]
> I think I mentioned we could do something like:
> 
> ![image](https://private-user-images.githubusercontent.com/58816/389460327-331016a5-bc0d-4b5c-a15c-47b643903d0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MzY5OTgsIm5iZiI6MTczMjUzNjY5OCwicGF0aCI6Ii81ODgxNi8zODk0NjAzMjctMzMxMDE2YTUtYmMwZC00YjVjLWExNWMtNDdiNjQzOTAzZDBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDEyMTEzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwOGY5Y2YwYTUxMmM3Zjc5YTRjNDNiOWI0NmQ3NTNmYjI3NGFlNjgxYzA0N2Y0MWQ2OWU0NmFkYjQ2YWI4NGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wPlirw0d08QxpazKF_tk0OAE4u-EMY_bf1AwCl2rdwg)
> 
> Getting the list of contributors and their avatars automatically from GitHub API.

I like a display like this and can use the GitHub API to display it. It represents Torrust as open source better than what we have at the moment. I often see the above as part of the home page, for example on the [Skeleton website](https://www.skeleton.dev/) so I would say it's more natural to have it on an existing page rather than on its own route as it is now.
