### ISSUE TITLE
Add contributor's articles to contributor's profile

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-website#123]
I think the idea was to include the contributor's articles on their profiles, but we still have this message:

![image](https://github.com/user-attachments/assets/a296457f-ffa0-4fca-b889-634f4322e5de)

**Comment by grmbyrn** [comment]
> I think the idea was to include the contributor's articles on their profiles, but we still have this message:
> 
> ![image](https://private-user-images.githubusercontent.com/58816/389461812-a296457f-ffa0-4fca-b889-634f4322e5de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1NDUzNDgsIm5iZiI6MTczMjU0NTA0OCwicGF0aCI6Ii81ODgxNi8zODk0NjE4MTItYTI5NjQ1N2YtZmZhMC00ZmNhLWI4ODktNjM0ZjQzMjJlNWRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDE0MzA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzZDFiYTM2OWI4ZmU4YTRkNTVhMTAyYTUzODk1ZGI0NzAwZjNiZDliOGYxZTczZmIwNGQwMGE3NGU4YWQ5OWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iT-fMNYATpMBWyyU2eDFUaYOdxDnr8LsJN3fWiuM12o)

Hi @josecelano it was displaying the contributor's articles but something might have changed when I was working on the routes. I'll see what it is.
