### ISSUE TITLE
Related Post section does not look like the standard blog post list

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-website#27]
Current:

![image](https://github.com/user-attachments/assets/956cc333-c811-40b8-8556-cc8c0d9b722f)

Expected:

I guess it should look like the latest articles grid on the homepage:

![image](https://github.com/user-attachments/assets/f4e7346f-f8cc-4892-bed8-dcbc114deea7)

We can ask Fer if he intentionally:

- Removed the post-short description
- Didn't include tags.

From cards. However, in the meantime, we should implement his exact design.

**Comment by josecelano** [comment]
Hi @grmbyrn, did you remove the "Related Post" section in the new [PR](https://github.com/torrust/torrust-website-v2/pull/44)? I don't see it anymore.

**Comment by grmbyrn** [comment]
> Hi @grmbyrn, did you remove the "Related Post" section in the new [PR](https://github.com/torrust/torrust-website-v2/pull/44)? I don't see it anymore.

Yes, I thought that since it wasn't in the design that it'd better to take it out. I can put it back in and adapt it if Fer decides to include it.

**Comment by fvdlc** [comment]
Hi @josecelano, @grmbyrn! If you need the related articles, we can use a modified version of the latest articles module on the homepage. Responsive logic would be the same. [Here's the design](https://www.figma.com/design/BtmAvPOHMCAGD1BzSSltNp/Torrust-website?node-id=699-1150&t=LzKFmiE7Te1Lc2cy-1).
