### ISSUE TITLE
Ask designer how to implement different types of callouts components

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-website#35]
Current:

![image](https://github.com/user-attachments/assets/ee400387-9d4d-4a58-ab74-cd9797796a25)

Also fix the link contrast in callouts:

![image](https://github.com/user-attachments/assets/e9dcdf3d-b627-479d-904f-d2f592a4a9f9)

Expected:

Not included in the design

**Comment by fvdlc** [comment]
@josecelano When are these callouts displayed?

**Comment by josecelano** [comment]
> @josecelano When are these callouts displayed?

Hi @fvalcruz in general in tutorials (or other blog posts) like:

https://v2.torrust.com/deploying-torrust-to-production

**Comment by fvdlc** [comment]
@josecelano Perfect. Do you need multiple types or just one (same color, same icon) to be integrated within the body of the article / wiki?

**Comment by fvdlc** [comment]
@josecelano Here's a [first take](https://www.figma.com/design/BtmAvPOHMCAGD1BzSSltNp/Torrust-website?node-id=699-1267&t=LzKFmiE7Te1Lc2cy-1). If you need additional variants (colors, other shapes, uses...), please let me know.
