### ISSUE TITLE
Ask the designer how to implement a link inside a key feature card

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-website#42]
Current:

![image](https://github.com/user-attachments/assets/81565c3b-7f8c-4f29-844e-80e1e5ec39cb)

Expected:

Not included in design.

**Comment by fvdlc** [comment]
I would not link individual elements within the card, but the whole card instead. We can make the border visible while hovering and make the card clickable. [Figma example](https://www.figma.com/design/BtmAvPOHMCAGD1BzSSltNp/Torrust-website?node-id=699-1264&t=LzKFmiE7Te1Lc2cy-1).

**Comment by josecelano** [comment]
Hi @grmbyrn, the hover border is 2px

![image](https://github.com/user-attachments/assets/c3518486-2782-44ae-a26b-b121955a59b4)

**Comment by josecelano** [comment]
Hi @grmbyrn this is still not working in https://github.com/torrust/torrust-website/pull/68. The link should be the whole card.

**Comment by grmbyrn** [comment]
> Hi @grmbyrn this is still not working in #68. The link should be the whole card.

Hi @josecelano I had it like that but changed it. I'll change it back to be a link for the whole card.
