### ISSUE TITLE
Ask the designer to review color

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-website#47]
The homepage, Index, and Tracker pages look too saturated in colour.

![image](https://github.com/user-attachments/assets/2578a0e8-f699-480e-a5f5-5e1255ea0084)

These are the colours in the brand manual:

![image](https://github.com/user-attachments/assets/aa59dd93-de78-4d0f-a23a-eaba33b30d85)

cc @da2ce7 @grmbyrn @fvalcruz

**Comment by da2ce7** [comment]
The colors are not rusty.

**Comment by josecelano** [comment]
The actual colour reminds an alert message like this:

![image](https://github.com/user-attachments/assets/5f550535-a077-4049-ac8e-d655cd438e48)

**Comment by fvdlc** [comment]
@josecelano The colors used in Figma are those provided by the brand designer. If you want to use a different color, I recommend contacting the brand designer.

**Comment by josecelano** [comment]
It depends on reviewing the brand guide colours.
