### ISSUE TITLE
Ask the designer about the blog post card

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-website#60]
Hi @fvalcruz, we don't know if the blog post cards should always have these backgrounds (gradient):

![image](https://github.com/user-attachments/assets/98989697-53c1-4e39-8a52-c14c6689b3ce)

or was it just a placeholder you used for the design, and we need to use the actual image?

cc @grmbyrn @cgbosse

**Comment by fvdlc** [comment]
@josecelano, @grmbyrn That "gradient" is generated by applying a blur filter to the feature image of the article. The goal was to allow you to use whatever image you like on the articles while keeping a consistent look in all places where the article card is shown.

Let me know if you have any questions.

**Comment by josecelano** [comment]
This was fixed:

![image](https://github.com/user-attachments/assets/3378fa48-eabe-4f7c-8948-c97263dc0d86)
