### ISSUE TITLE
v1 error page in v2

### ISSUE THREAD

**Issue by grmbyrn** [torrust/torrust-website#71]
I see that the error page is carried over from v1 of the website. Should we continue with this or change it for something else? @josecelano @fvalcruz 

![Screenshot 2024-10-03 at 14 22 06](https://github.com/user-attachments/assets/52a071b8-882a-4b05-8757-59de42206b06)

**Comment by josecelano** [comment]
Hi @grmbyrn I would change it to a dark mode that aligns with the new design.
