### ISSUE TITLE
Migrate `shiki-es` dep to `shikiji`

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-website#76]
https://www.npmjs.com/package/shiki-es package has been deprecated. Migrate to https://github.com/antfu/shikiji

![image](https://github.com/torrust/torrust-website/assets/58816/f2bbe009-3ed6-45e1-9448-a36428fa0b3b)

**Comment by grmbyrn** [comment]
Hi @josecelano I've been working on how to migrate from `shiki-es` to `shikiji` as recommended. I have found that `shinjiki` is also deprecated as both have been merged back into `Shiki 1`. However, I think that the warning is coming from `Histoire` and not from our implementation of it.

I checked the `Histoire` repo and found that a [PR](https://github.com/histoire-dev/histoire/pull/683) was made to migrate it in February but it's not passing Nuxt 3 tests so hasn't been merged.

**Comment by josecelano** [comment]
> Hi @josecelano I've been working on how to migrate from `shiki-es` to `shikiji` as recommended. I have found that `shinjiki` is also deprecated as both have been merged back into `Shiki 1`. However, I think that the warning is coming from `Histoire` and not from our implementation of it.
> 
> I checked the `Histoire` repo and found that a [PR](https://github.com/histoire-dev/histoire/pull/683) was made to migrate it in February but it's not passing Nuxt 3 tests so hasn't been merged.

OK @grmbyrn we can wait until it's merged.
