### ISSUE TITLE
Review design for table of contents in blog posts

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-website#8]
In the original design, Fer did not use any char at the beginning of the title of the table of contents item. We are using `#`. Do we need that char @grmbyrn?

### Current

![image](https://github.com/user-attachments/assets/4c1f5044-5e71-4bea-9f75-35f7e0c19362)

### Expected

![image](https://github.com/user-attachments/assets/27f64900-4863-4a86-88ce-06cd57e3ddb8)

**Comment by josecelano** [comment]
Hi @grmbyrn in this [PR](https://github.com/torrust/torrust-website-v2/pull/44), some articles still have a table of contents with the `#` prefix.

http://localhost:5173/torrust-enhancing-the-bittorrent-ecosystem

![image](https://github.com/user-attachments/assets/d88c97ae-d107-41ab-8bb7-79fe35c3cf37)

**Comment by grmbyrn** [comment]
> Hi @grmbyrn in this [PR](https://github.com/torrust/torrust-website-v2/pull/44), some articles still have a table of contents with the `#` prefix.
> 
> http://localhost:5173/torrust-enhancing-the-bittorrent-ecosystem
> 
> ![image](https://private-user-images.githubusercontent.com/58816/370798915-d88c97ae-d107-41ab-8bb7-79fe35c3cf37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyODExNzYsIm5iZiI6MTcyNzI4MDg3NiwicGF0aCI6Ii81ODgxNi8zNzA3OTg5MTUtZDg4Yzk3YWUtZDEwNy00MWFiLThiYjctNzlmZTM1YzNjZjM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDE2MTQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2NTAwNDk5MmZmOWZlM2QxMGFjMDhhMDMwNmQwMjgxZWNjYzM5MGU0Y2Q1MGE2ZDY0NzBjMTA5NWEzNGFiNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rOSmCo77Xu90etZYlFSBzhOs-JxJRwLLH2M3hhI0hFM)

Hi @josecelano at the moment the blog posts are using a different table of contents set up. I've got it to work on `pages` but will need to see if it works on Markdown.

**Comment by josecelano** [comment]
> > Hi @grmbyrn in this [PR](https://github.com/torrust/torrust-website-v2/pull/44), some articles still have a table of contents with the `#` prefix.
> > http://localhost:5173/torrust-enhancing-the-bittorrent-ecosystem
> > ![image](https://private-user-images.githubusercontent.com/58816/370798915-d88c97ae-d107-41ab-8bb7-79fe35c3cf37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyODExNzYsIm5iZiI6MTcyNzI4MDg3NiwicGF0aCI6Ii81ODgxNi8zNzA3OTg5MTUtZDg4Yzk3YWUtZDEwNy00MWFiLThiYjctNzlmZTM1YzNjZjM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDE2MTQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2NTAwNDk5MmZmOWZlM2QxMGFjMDhhMDMwNmQwMjgxZWNjYzM5MGU0Y2Q1MGE2ZDY0NzBjMTA5NWEzNGFiNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rOSmCo77Xu90etZYlFSBzhOs-JxJRwLLH2M3hhI0hFM)
> 
> Hi @josecelano at the moment the blog posts are using a different table of contents set up. I've got it to work on `pages` but will need to see if it works on Markdown.

Ok @grmbyrn we can keep the issue until it's fixed for this case. I've updated the title.

**Comment by josecelano** [comment]
This was fixed:

![image](https://github.com/user-attachments/assets/eb7801be-5708-4077-a60e-6b43ba1bdbe6)
