### ISSUE TITLE
Top Left Torrust Logo-Home-Button Visual Feedback

### ISSUE THREAD

**Issue by da2ce7** [torrust/torrust-website#93]
There is no visual feedback that the top-left `Torrust` is a button.
There is no visual feedback that we have navigated to the `Home` page on the `Torrust` top-left logo.

**Comment by cgbosse** [comment]
@da2ce7 that is a good point.
We do not need Fer for this issue I believe, don´t you think so @josecelano?
I think that this is more a point for Graeme though he can just create this menu element in the top and it will show.

**Comment by cgbosse** [comment]
Sent by Fer: 
![image](https://github.com/user-attachments/assets/59be9e56-185f-4baa-b0c5-b52662e98042)

![image](https://github.com/user-attachments/assets/a2defce7-ea8c-41e4-9567-db3899935ce9)
