### ISSUE TITLE
Bottom Nautilus Logo is not a link, and has no visual feedback it it should be link.

### ISSUE THREAD

**Issue by da2ce7** [torrust/torrust-website#95]

**Comment by cgbosse** [comment]
@grmbyrn 

make anyone who hoovers over this section display the clickable hand as with the logo on the top, and link it to our Nautilus Website.

![image](https://github.com/user-attachments/assets/14c985cd-ae0c-42c9-b6ff-ab0020e939b2)

**Comment by cgbosse** [comment]
Fer suggest this for example:

https://www.figma.com/design/BtmAvPOHMCAGD1BzSSltNp/Torrust-website?node-id=793-992&node-type=frame

**Comment by cgbosse** [comment]
![image](https://github.com/user-attachments/assets/fb9b882b-fd32-421b-911d-12fc11124121)

https://www.figma.com/design/BtmAvPOHMCAGD1BzSSltNp/Torrust-website?node-id=793-992&node-type=frame

**Comment by josecelano** [comment]
> Fer suggest this for example:
> 
> https://www.figma.com/design/BtmAvPOHMCAGD1BzSSltNp/Torrust-website?node-id=793-992&node-type=frame

![image](https://github.com/user-attachments/assets/43a70087-c409-416a-841d-4a513212b4f8)
